// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_G9N2PkFzv-1Ektvu2PesTkyjERKxsY',
    appId: '1:1091152785269:android:4f86fd4b71dedf9c0bad3c',
    messagingSenderId: '1091152785269',
    projectId: 'xp68-cd001',
    storageBucket: 'xp68-cd001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB26FQtN8cPnlmRpgUW4FJlxMg8v25R31s',
    appId: '1:1091152785269:ios:b1a598dd791247e60bad3c',
    messagingSenderId: '1091152785269',
    projectId: 'xp68-cd001',
    storageBucket: 'xp68-cd001.appspot.com',
    iosBundleId: 'com.example.appFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB26FQtN8cPnlmRpgUW4FJlxMg8v25R31s',
    appId: '1:1091152785269:ios:d780fe849603aaf40bad3c',
    messagingSenderId: '1091152785269',
    projectId: 'xp68-cd001',
    storageBucket: 'xp68-cd001.appspot.com',
    iosBundleId: 'com.example.appFirebaseTutorial.RunnerTests',
  );
}
